name: NodeJS Lambda AWS CI CD
on: [push]
jobs:
  deploy_source:
    name: Build and Deploy App
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout Latest from Git 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Generating Code Bundle(zip)
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./my-func-bundle.zip ./          
      - name: Deploy Bundle to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: my-func
          zip_file: my-func-bundle.zip
